DemoNNS/Models/ErrorViewModel.cs
namespace DemoNNS.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

DemoNNS/Models/Person.cs
using System. ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace DemoNNS.Models
{
    [Table("Persons")]
    public class Person
    {
        [Key]
        public int ID{ get; set; }
        public string FullName{ get; set; }
        public string Address{ get; set;}
        public DateTime BirthDay{ get; set; }

    }
}

DemoNNS/Models/Student.cs
using System. ComponentModel.DataAnnotations;
namespace DemoNNS.Models
{
    public class Student
    {
        [Key]
        public string StudentID { get; set;}
        public string StudentName { get; set;}
    }
}

DemoNNS/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;
namespace DemoNNS.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(string FullName, string Address)
        {
            ViewBag. thongbao = "Xin Chao" + FullName + "_" + Address;
            return View();
        }
    }
}

DemoNNS/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DemoNNS.Models;

namespace DemoNNS.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Privacy()
    {
        return View();
    }
    public IActionResult Demoo()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DemoNNS/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using DemoNNS.Models;

namespace DemoNNS.Controllers
{
    public class PersonController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Person ps)
        {
            string message = ps.FullName + "_" + ps.ID;
            ViewBag.thongbao = message;
            return View();
        }
    }
}

DemoNNS/Controllers/StudentController.cs
using DemoNNS.Models;
using Microsoft.AspNetCore.Mvc;
using DemoNNS.Data;
using Microsoft.EntityFrameworkCore;

namespace DemoNNS.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private string id;

        public StudentController (ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.Students.ToListAsync();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Student std)
        {
            if(ModelState.IsValid)
            {
                _context.Add(std);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(std);
        }
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
        
            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("StrudentID, StudentName")] Student std)
        {
            if(id != std.StudentID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(std);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(std.StudentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(std); 
        }
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
                {
                    return NotFound();
                }
            var std = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentID == id);
            if (std == null)
                {
                    return NotFound();
                }
            return View(std);
        }
        private bool StudentExists(string studentID)
        {
            return _context.Students.Any(e => e.StudentID == id);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var std = await _context.Students.FindAsync(id);
            _context.Students.Remove(std);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

DemoNNS/Views/Demo/index.cshtml
<h2>Nhap Du Lieu De Gui Len Controller</h2>
<form asp-action="Index"> 
    <label>Nhap Ho Va Ten</label>
    <input type="text" name="FullName">
    <br>
    <label>Nhap Vao Dia Chi</label>
    <input type="text" name="Address">
    <br>
    <input type="submit" value="Enter" class="btn btn-success">
</form>
<h3>@ViewBag.thongbao</h3>

DemoNNS/Views/Home/Demoo.cshtml
<h2>View Demo</h2>

DemoNNS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoNNS/Views/Person/index.cshtml
<form asp-action="Index" method="post">
    <label>ID:</label>
    <input type="text" name="ID">
    <br>
    <label>FullName:</label>
    <input type="text" name="FullName">
    <br>
    <label>BirthDay:</label>
    <input type="date" name="BirthDay">
    <br>
    <input type="submit" value="Gui Du Lieu">
</form>

DemoNNS/Views/Shared/NotFound.cshtml
<div class="text-center">
    <h2>Da Xay Ra Loi Trong Khi Xu Ly Yeu Cau Cua Ban</h2>
    <hr>
    <a class="btn btn-success" asp-controller="Home" asp-action="Index">Trang Chu</a>
</div>

DemoNNS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoNNS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoNNS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoNNS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="Index">Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DemoNNS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DemoNNS/Views/Student/Create.cshtml
@model DemoNNS.Models.Student
<h1>Tao Moi Mot Sinh Vien</h1>
<hr>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <input asp-for="StudentID" class="form-control">
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control">
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Save">
                <a class="btn btn-success" asp-action="Index">Danh Sach Sinh Vien</a>
            </div>
        </form>
    </div>
</div>

DemoNNS/Views/Student/Delete.cshtml
@model DemoNNS.Models.Student

@{
    ViewData["Tille"] = "Delete";
}

<h3>Ban co muon xoa thong tin sinh vien khong</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentName):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StudentID" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-success" asp-action="Index">Danh Sach Sinh vien</a>
    </form>
</div>

DemoNNS/Views/Student/Edit.cshtml
@model DemoNNS.Models.Student
@{
    ViewData["Title"] = "Edit";
}
<h1>Sua Thong Tin Sinh Vien</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentID" />
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control">
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Save">
                <a class="btn btn-success" asp-action="Index">Danh Sach Sinh Vien</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoNNS/Views/Student/Index.cshtml
@model IEnumerable<DemoNNS.Models.Student>
    <p>
        <a class="btn btn-sucess" asp-action="Create">Create a new student</a>
    </p>
    <table class="table table-all">
        <tr>
            <tr>Student ID</tr>
            <tr>Student Name</tr>
            <tr></tr>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.StudentID)</td>
                <td>@Html.DisplayFor(m => item.StudentName)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.StudentID">Sua</a>
                    <a asp-action="Delete" asp-route-id="@item.StudentID">Xoa</a>
                </td>
            </tr>
        }
    </table>